HH_FIELD_SPANS:  # Byte positions taken from the data layout excel sheet
  schedule_id: [0, 3]
  fsu_serial_no: [3, 8]
  schedule: [8, 11]
  survey_year: [11, 15]
  sector: [15, 16]
  nss_region: [16, 19]
  district: [19, 21]
  stratum: [21, 24]
  sub_stratum: [24, 27]
  sub_round: [27, 28]
  fod_sub_region: [28, 32]
  sample_hh_no: [32, 34]
  informant_sl_no: [34, 37]
  response_code: [37, 38]
  survey_code: [38, 39]
  reason_substitution_hh: [39, 40]
  hh_size: [40, 43]
  religion: [43, 44]
  social_group: [44, 45]
  land_possessed: [45, 47]
  ce_household_monthly: [47, 57]
  imputed_monthly_consumption_home_grown_stock: [57, 67]
  imputed_monthly_consumption_wages_free_gifts: [67, 77]
  ce_annual_clothing_footwear: [77, 87]
  ce_annual_durable_goods: [87, 97]
  total_monthly_ce: [97, 107]
  energy_cooking: [107, 109]
  energy_lighting: [109, 110]
  washing_type: [110, 111]
  sweeping_type: [111, 112]
  dwelling_unit: [112, 113]
  dwelling_unit_structure_type: [113, 114]
  special_care_needed_in_hh: [114, 115]
  caregiver_available_in_hh: [115, 116]
  time_to_canvass: [116, 119]
  nsc: [119, 122]
  mult: [122, 132]

SECTOR:
  1: Rural
  2: Urban

STATES:
  "01": Jammu & Kashmir
  "02": Himachal Pradesh
  "03": Punjab
  "04": Chandigarh
  "05": Uttarakhand
  "06": Haryana
  "07": Delhi
  "08": Rajasthan
  "09": Uttar Pradesh
  "10": Bihar
  "11": Sikkim
  "12": Arunachal Pradesh
  "13": Nagaland
  "14": Manipur
  "15": Mizoram
  "16": Tripura
  "17": Meghalaya
  "18": Assam
  "19": West Bengal
  "20": Jharkhand
  "21": Odisha
  "22": Chhattisgarh
  "23": Madhya Pradesh
  "24": Gujarat
  "25": D & N. Haveli & Daman & Diu
  "27": Maharashtra
  "28": Andhra Pradesh
  "29": Karnataka
  "30": Goa
  "31": Lakshadweep
  "32": Kerala
  "33": Tamilnadu
  "34": Puduchery
  "35": Andaman & N. Island
  "36": Telangana
  "37": Ladakh

RESPONSE_CODE:
  1: informant co-operative and capable
  2: informant co-operative but not capable
  3: informant busy
  4: informant reluctant
  9: others

SURVEY_CODE:
  1: original
  2: substitute
  3: casualty

REASON_SUBSTITUTION_HH:
  1: informant busy
  2: members away from home
  3: informant non co-operative
  9: others

RELIGION:
  1: Hinduism
  2: Islam
  3: Christianity
  4: Sikhism
  5: Jainism
  6: Buddhism
  7: Zoroastrianism
  9: others

SOCIAL_GROUP:
  1: scheduled tribe
  2: scheduled caste
  3: other backward class
  9: others

LAND_POSSESSED:
  1: less than 0.01 acre
  2: 0.01 - 0.05 acre
  3: 0.05 - 0.5 acre
  4: 0.5 - 1.0 acre
  5: 1.0 - 2.5 acre
  6: 2.5 - 5.0 acre
  7: 5.0 - 7.5 acre
  8: 7.5 - 10.0 acre
  10: 10.0 - 15.0 acre
  11: 15.0 - 20.0 acre
  12: greater than or equal to 20 acre
  99: no land possessed

ENERGY_COOKING:
  1: firewood and chips
  2: LPG
  3: other natural gas
  4: dung cake
  5: kerosene
  6: coke or coal
  7: gobar gas
  8: biogas
  10: charcoal
  11: electricity (incl. generated by solar or wind power generators)
  12: no cooking arrangement
  19: others

ENERGY_LIGHTING:
  1: electricity
  2: kerosene
  3: other oil
  4: gas
  5: candle
  6: no lighting arrangement
  9: others

WASHING_TYPE:
  1: mechanical by hh members
  2: manual by hh members
  3: outsourced

SWEEPING_TYPE:
  1: mechanical by hh members
  2: manual by hh members
  3: outsourced

DWELLING_UNIT:
  1: owned
  2: hired
  4: no dwelling unit
  9: others

DWELLING_UNIT_STRUCTURE_TYPE:
  1: kutcha
  2: semi-pucca
  3: pucca

SPECIAL_CARE_NEEDED_IN_HH: &YESNO
  1: "yes"
  2: "no"

CAREGIVER_AVAILABLE_IN_HH: *YESNO

PERSON_FIELD_SPANS:
  schedule_id: [0, 3]
  fsu_serial_no: [3, 8]
  schedule: [8, 11]
  survey_year: [11, 15]
  sector: [15, 16]
  nss_region: [16, 19]
  district: [19, 21]
  stratum: [21, 24]
  sub_stratum: [24, 27]
  sub_round: [27, 28]
  fod_sub_region: [28, 32]
  sample_hh_no: [32, 34]
  person_serial_no: [34, 37]
  relation_to_hoh: [37, 38]
  gender: [38, 39]
  age: [39, 42]
  marital_status: [42, 43]
  education: [43, 45]
  usual_principal_activity_status: [45, 47]
  nic_2008_principal_activity: [47, 49]
  member_srl_no: [49, 52]
  age2: [52, 55]
  informant_sl_no: [55, 58]
  gender_informant: [58, 59]
  day_of_week: [59, 60]
  type_of_day: [60, 61]
  person_response_code: [61, 62]
  member_srl_no2: [62, 65]
  age3: [65, 68]
  activity_srl_no: [68, 71]
  time_from: [71, 76]
  time_to: [76, 81]
  performed_multiple_activities: [81, 82]
  performed_simultaneous_activities: [82, 83]
  major_minor_activity: [83, 84]
  activity_code: [84, 87]
  where_activity_performed: [87, 88]
  paid_unpaid_status: [88, 90]
  enterprise_type: [90, 91]
  nsc: [91, 94]
  mult: [94, 104]

RELATION_TO_HOH:
  1: self
  2: spouse of head
  3: married child
  4: spouse of married child
  5: unmarried child
  6: grandchild

GENDER:
  1: male
  2: female
  3: transgender

MARITAL_STATUS:
  1: never married
  2: currently married
  3: widowed
  4: divorced/separated

EDUCATION:
  01: not literate
  02: below primary
  03: primary
  04: upper primary/middle
  05: secondary
  06: higher secondary
  07: diploma /certificate course (up to secondary)
  08: diploma/certificate course (higher secondary)
  10: diploma/certificate course(graduation & above)
  11: graduate
  12: post graduate and above

USUAL_PRINCIPAL_ACTIVITY_STATUS:
  11: own account worker
  12: employer
  21: worked as helper in household enterprise (unpaid family worker)
  31: worked as regular salaried/ wage employee
  41: "worked as casual wage labour: in public works"
  51: "worked as casual wage labour: in other types of work"
  81: did not work but was seeking and/or available for work
  91: attended educational institution
  92: attended domestic duties only
  93: attended domestic duties and was also engaged in free collection of goods (vegetables, roots, firewood, cattle feed, etc.), sewing, tailoring, weaving, etc. for household use
  94: rentiers, pensioners , remittance recipients, etc.
  95: not able to work due to disability
  97: others (including begging, prostitution, etc.)

DAY_OF_WEEK:
  1: Monday
  2: Tuesday
  3: Wednesday
  4: Thursday
  5: Friday
  6: Saturday
  7: Sunday

TYPE_OF_DAY:
  1: normal day
  2: other day

PERSON_RESPONSE_CODE:
  1: cooperative
  2: non-cooperative

PERFORMED_MULTIPLE_ACTIVITIES: *YESNO
PERFORMED_SIMULTANEOUS_ACTIVITIES: *YESNO
MAJOR_MINOR_ACTIVITY:
  1: major
  2: minor

WHERE_ACTIVITY_PERFORMED:
  1: within premises of the dwelling unit of the selected household
  2: "outside premises of the dwelling unit of the selected household: in fixed location -2"
  3: "in non-fixed location"

PAID_UNPAID_STATUS:
  1: self development / self care / self maintenance, etc.
  2: care for children, sick, elderly, differently-abled persons in own households
  3: production of other services (except care activities as covered in code 02) for own consumption
  4: production of goods for own consumption
  5: voluntary work for production of goods in households
  6: voluntary work for production of services in households
  7: voluntary work for production of goods in market/non-market units
  8: voluntary work for production of services in market/non-market units
  9: unpaid trainee work for production of goods
  10: unpaid trainee work for production of services
  11: other unpaid work for production of goods
  12: other unpaid work for production of services
  13: self-employment for production of goods
  14: self-employment for production of services
  15: regular wage/salary for production of goods
  16: regular wage/salary for production of services
  17: casual labour for production of goods
  18: casual labour for production of services

ENTERPRISE_TYPE:
  1: proprietary
  2: partnership
  3: Government/local body
  4: Autonomous Bodies
  5: Public/Private limited company
  6: Co-operative societies
  7: trust/other non-profit institutions
  8: employer’s households (i.e., private households employing maid servant, watchman, cook, etc.)
  9: others
